import maya.cmds as cmds


mGear = [
    'root_C0_0_jnt', 
    'spine_C0_pelvis_jnt', 
    'spine_C0_spine_01_jnt', 
    'spine_C0_spine_02_jnt', 
    'spine_C0_spine_03_jnt', 
    'spine_C0_spine_04_jnt', 
    'spine_C0_spine_05_jnt', 
    'neck_C0_0_jnt', 
    'neck_C0_2_jnt', 
    'neck_C0_head_jnt',
    'clavicle_L0_clavicle_jnt', 
    'arm_L0_upperarm_jnt', 
    'arm_L0_lowerarm_jnt', 
    'arm_L0_hand_jnt',
    'thumb_L0_thumb_01_jnt', 
    'thumb_L0_thumb_02_jnt', 
    'thumb_L0_thumb_03_jnt',
    'index_metacarpal_L0_index_metacarpal_jnt', 
    'index_L0_index_01_jnt', 
    'index_L0_index_02_jnt', 
    'index_L0_index_03_jnt',
    'middle_metacarpal_L0_middle_metacarpal_jnt', 
    'middle_L0_middle_01_jnt', 
    'middle_L0_middle_02_jnt', 
    'middle_L0_middle_03_jnt',
    'ring_metacarpal_L0_ring_metacarpal_jnt', 
    'ring_L0_ring_01_jnt', 
    'ring_L0_ring_02_jnt', 
    'ring_L0_ring_03_jnt',
    'pinky_metacarpal_L0_pinky_metacarpal_jnt', 
    'pinky_L0_pinky_01_jnt', 
    'pinky_L0_pinky_02_jnt', 
    'pinky_L0_pinky_03_jnt',
    'clavicle_R0_clavicle_jnt', 
    'arm_R0_upperarm_jnt', 
    'arm_R0_lowerarm_jnt', 
    'arm_R0_hand_jnt', 
    'thumb_R0_thumb_01_jnt', 
    'thumb_R0_thumb_02_jnt', 
    'thumb_R0_thumb_03_jnt', 
    'index_metacarpal_R0_index_metacarpal_jnt', 
    'index_R0_index_01_jnt', 
    'index_R0_index_02_jnt', 
    'index_R0_index_03_jnt', 
    'middle_metacarpal_R0_middle_metacarpal_jnt', 
    'middle_R0_middle_01_jnt', 
    'middle_R0_middle_02_jnt', 
    'middle_R0_middle_03_jnt', 
    'ring_metacarpal_R0_ring_metacarpal_jnt', 
    'ring_R0_ring_01_jnt', 
    'ring_R0_ring_02_jnt', 
    'ring_R0_ring_03_jnt', 
    'pinky_metacarpal_R0_pinky_metacarpal_jnt', 
    'pinky_R0_pinky_01_jnt', 
    'pinky_R0_pinky_02_jnt', 
    'pinky_R0_pinky_03_jnt',
    'leg_L0_thigh_jnt', 
    'leg_L0_calf_jnt', 
    'leg_L0_foot_jnt', 
    'foot_L0_ball_jnt',
    'leg_R0_thigh_jnt', 
    'leg_R0_calf_jnt', 
    'leg_R0_foot_jnt', 
    'foot_R0_ball_jnt'

    ]



metaS = [
    'root', 
    'pelvis', 
    'spine_01', 
    'spine_02', 
    'spine_03', 
    'spine_04', 
    'spine_05', 
    'neck_01', 
    'neck_02', 
    'head',
    'clavicle_l', 
    'upperarm_l', 
    'lowerarm_l', 
    'hand_l',
    'thumb_01_l', 
    'thumb_02_l', 
    'thumb_03_l',
    'index_metacarpal_l', 
    'index_01_l', 
    'index_02_l', 
    'index_03_l',
    'middle_metacarpal_l', 
    'middle_01_l', 
    'middle_02_l', 
    'middle_03_l',
    'ring_metacarpal_l', 
    'ring_01_l', 
    'ring_02_l', 
    'ring_03_l',
    'pinky_metacarpal_l', 
    'pinky_01_l', 
    'pinky_02_l', 
    'pinky_03_l',
    'clavicle_r', 
    'upperarm_r', 
    'lowerarm_r', 
    'hand_r', 
    'thumb_01_r', 
    'thumb_02_r', 
    'thumb_03_r', 
    'index_metacarpal_r', 
    'index_01_r', 
    'index_02_r', 
    'index_03_r', 
    'middle_metacarpal_r', 
    'middle_01_r', 
    'middle_02_r', 
    'middle_03_r', 
    'ring_metacarpal_r', 
    'ring_01_r', 
    'ring_02_r', 
    'ring_03_r', 
    'pinky_metacarpal_r', 
    'pinky_01_r', 
    'pinky_02_r', 
    'pinky_03_r',
    'thigh_l', 
    'calf_l', 
    'foot_l', 
    'ball_l',
    'thigh_r', 
    'calf_r', 
    'foot_r', 
    'ball_r'
    ]



cmds.select(cl=True)
if cmds.objExists('toDel'):
    toDel = 'toDel'
else:
    toDel = cmds.createNode('transform', n='toDel')


for s, t in zip(mGear, metaS):
    pnt = cmds.pointConstraint(s, t, mo=1)
    cmds.parent(pnt, toDel)
    ori = cmds.orientConstraint(s,t, mo=1)
    cmds.parent(ori, toDel)

