# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\OGFedoseeva\Documents\maya\scripts\OWL_Anim_ToolKit\add_new_project.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main_layout(object):
    def setupUi(self, main_layout):
        main_layout.setObjectName("main_layout")
        main_layout.resize(598, 212)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        main_layout.setFont(font)
        self.add_proj_label = QtWidgets.QLabel(main_layout)
        self.add_proj_label.setGeometry(QtCore.QRect(166, 10, 251, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(11)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.add_proj_label.setFont(font)
        self.add_proj_label.setAlignment(QtCore.Qt.AlignCenter)
        self.add_proj_label.setObjectName("add_proj_label")
        self.add_new_proj_btn = QtWidgets.QPushButton(main_layout)
        self.add_new_proj_btn.setGeometry(QtCore.QRect(20, 160, 551, 31))
        self.add_new_proj_btn.setObjectName("add_new_proj_btn")
        self.gridLayoutWidget = QtWidgets.QWidget(main_layout)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 40, 581, 109))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.local_path_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.local_path_label.setObjectName("local_path_label")
        self.gridLayout.addWidget(self.local_path_label, 1, 0, 1, 1)
        self.project_name_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.project_name_label.setObjectName("project_name_label")
        self.gridLayout.addWidget(self.project_name_label, 0, 0, 1, 1)
        self.proj_path_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.proj_path_label.setObjectName("proj_path_label")
        self.gridLayout.addWidget(self.proj_path_label, 2, 0, 1, 1)
        self.local_path_set_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.local_path_set_btn.setObjectName("local_path_set_btn")
        self.gridLayout.addWidget(self.local_path_set_btn, 1, 3, 1, 1)
        self.project_path_set_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.project_path_set_btn.setObjectName("project_path_set_btn")
        self.gridLayout.addWidget(self.project_path_set_btn, 2, 3, 1, 1)
        self.project_path_line_edit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.project_path_line_edit.setText("")
        self.project_path_line_edit.setObjectName("project_path_line_edit")
        self.gridLayout.addWidget(self.project_path_line_edit, 2, 1, 1, 1)
        self.export_anim_folder_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.export_anim_folder_label.setObjectName("export_anim_folder_label")
        self.gridLayout.addWidget(self.export_anim_folder_label, 3, 0, 1, 1)
        self.export_anim_folder_line_edit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.export_anim_folder_line_edit.setText("")
        self.export_anim_folder_line_edit.setObjectName("export_anim_folder_line_edit")
        self.gridLayout.addWidget(self.export_anim_folder_line_edit, 3, 1, 1, 1)
        self.local_path_line_edit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.local_path_line_edit.setObjectName("local_path_line_edit")
        self.gridLayout.addWidget(self.local_path_line_edit, 1, 1, 1, 1)
        self.project_name_line_edit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.project_name_line_edit.setObjectName("project_name_line_edit")
        self.gridLayout.addWidget(self.project_name_line_edit, 0, 1, 1, 1)
        self.export_anim_folder_set_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.export_anim_folder_set_btn.setObjectName("export_anim_folder_set_btn")
        self.gridLayout.addWidget(self.export_anim_folder_set_btn, 3, 3, 1, 1)

        self.retranslateUi(main_layout)
        QtCore.QMetaObject.connectSlotsByName(main_layout)

    def retranslateUi(self, main_layout):
        _translate = QtCore.QCoreApplication.translate
        main_layout.setWindowTitle(_translate("main_layout", "Form"))
        self.add_proj_label.setText(_translate("main_layout", "Add New Project"))
        self.add_new_proj_btn.setText(_translate("main_layout", "ADD NEW PROJECT"))
        self.local_path_label.setText(_translate("main_layout", "Local Path:"))
        self.project_name_label.setText(_translate("main_layout", "Project Name:"))
        self.proj_path_label.setText(_translate("main_layout", "Project Path:"))
        self.local_path_set_btn.setText(_translate("main_layout", "Set"))
        self.project_path_set_btn.setText(_translate("main_layout", "Set"))
        self.project_path_line_edit.setPlaceholderText(_translate("main_layout", "Set path where the project files are located on your computer."))
        self.export_anim_folder_label.setText(_translate("main_layout", "Export Folder:"))
        self.export_anim_folder_line_edit.setPlaceholderText(_translate("main_layout", "Set path where you want to export your animation files to."))
        self.local_path_line_edit.setPlaceholderText(_translate("main_layout", "Set path where the SVN project files are located on your computer."))
        self.project_name_line_edit.setPlaceholderText(_translate("main_layout", "Enter Name of new Project"))
        self.export_anim_folder_set_btn.setText(_translate("main_layout", "Set"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    main_layout = QtWidgets.QWidget()
    ui = Ui_main_layout()
    ui.setupUi(main_layout)
    main_layout.show()
    sys.exit(app.exec_())
