# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\OGFedoseeva\Documents\maya\scripts\OWL_Anim_ToolKit\convertWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 297)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(120, 0, 151, 31))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 29, 381, 121))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.converter_layout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.converter_layout.setContentsMargins(0, 0, 0, 0)
        self.converter_layout.setObjectName("converter_layout")
        self.arrow_label_a = QtWidgets.QLabel(self.gridLayoutWidget)
        self.arrow_label_a.setAlignment(QtCore.Qt.AlignCenter)
        self.arrow_label_a.setObjectName("arrow_label_a")
        self.converter_layout.addWidget(self.arrow_label_a, 0, 2, 1, 1)
        self.from_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.from_label.setObjectName("from_label")
        self.converter_layout.addWidget(self.from_label, 0, 0, 1, 1)
        self.source_character_combobox = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.source_character_combobox.setObjectName("source_character_combobox")
        self.converter_layout.addWidget(self.source_character_combobox, 1, 1, 1, 1)
        self.source_project_combobox = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.source_project_combobox.setObjectName("source_project_combobox")
        self.converter_layout.addWidget(self.source_project_combobox, 0, 1, 1, 1)
        self.to_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.to_label.setObjectName("to_label")
        self.converter_layout.addWidget(self.to_label, 0, 3, 1, 1)
        self.target_project_combobox_2 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.target_project_combobox_2.setObjectName("target_project_combobox_2")
        self.converter_layout.addWidget(self.target_project_combobox_2, 1, 4, 1, 1)
        self.arrow_label_b = QtWidgets.QLabel(self.gridLayoutWidget)
        self.arrow_label_b.setAlignment(QtCore.Qt.AlignCenter)
        self.arrow_label_b.setObjectName("arrow_label_b")
        self.converter_layout.addWidget(self.arrow_label_b, 1, 2, 1, 1)
        self.target_project_combobox = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.target_project_combobox.setObjectName("target_project_combobox")
        self.converter_layout.addWidget(self.target_project_combobox, 0, 4, 1, 1)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 159, 381, 131))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.convert_current_anim_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.convert_current_anim_btn.setObjectName("convert_current_anim_btn")
        self.verticalLayout.addWidget(self.convert_current_anim_btn)
        self.convert_batch_anim_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.convert_batch_anim_btn.setObjectName("convert_batch_anim_btn")
        self.verticalLayout.addWidget(self.convert_batch_anim_btn)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Animation Converter"))
        self.arrow_label_a.setText(_translate("Form", "-->"))
        self.from_label.setText(_translate("Form", "From:"))
        self.source_project_combobox.setPlaceholderText(_translate("Form", "Source Project"))
        self.to_label.setText(_translate("Form", "To:"))
        self.arrow_label_b.setText(_translate("Form", "-->"))
        self.target_project_combobox.setPlaceholderText(_translate("Form", "Target Project"))
        self.convert_current_anim_btn.setText(_translate("Form", "Convert Current Animation"))
        self.convert_batch_anim_btn.setText(_translate("Form", "Convert Batch"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
